const PDFDocument = require('pdfkit');
const db = require('./db');

/**
 * Generate a patient health report PDF
 * @param {string} userId - LINE user ID
 * @returns {Promise<Buffer>} PDF buffer
 */
const generateReport = async (userId) => {
    return new Promise(async (resolve, reject) => {
        try {
            // Fetch Patient Data
            const patientRes = await db.query('SELECT * FROM chronic_patients WHERE line_user_id = $1', [userId]);
            const patient = patientRes.rows[0];

            if (!patient) throw new Error('Patient not found');

            // Fetch Health Stats (Last 30 days)
            const statsRes = await db.query(`
                SELECT 
                    COUNT(*) as total_checkins,
                    AVG(glucose_level) as avg_glucose,
                    SUM(CASE WHEN medication_taken = true THEN 1 ELSE 0 END) as meds_taken,
                    SUM(CASE WHEN medication_taken = false THEN 1 ELSE 0 END) as meds_missed,
                    COUNT(CASE WHEN symptoms IS NOT NULL AND symptoms != '' THEN 1 END) as symptom_reports
                FROM check_ins
                WHERE line_user_id = $1 
                AND check_in_time >= NOW() - INTERVAL '30 days'
            `, [userId]);
            const stats = statsRes.rows[0];

            // Create PDF
            const doc = new PDFDocument({ size: 'A4', margin: 50 });
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            // --- Header ---
            doc.font('Helvetica-Bold').fontSize(20).text('Hanna Health Report', { align: 'center' });
            doc.moveDown();
            doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
            doc.moveDown();

            // --- Patient Info ---
            doc.rect(50, 100, 500, 80).stroke();
            doc.text(`Name: ${patient.name || patient.display_name || 'N/A'}`, 60, 110);
            doc.text(`Age: ${patient.age || 'N/A'}`, 60, 130);
            doc.text(`Condition: ${patient.condition || 'N/A'}`, 60, 150);
            doc.text(`ID: ${userId.substring(0, 8)}...`, 300, 110);

            // --- Summary Stats ---
            doc.moveDown(4);
            doc.font('Helvetica-Bold').fontSize(16).text('30-Day Summary');
            doc.moveDown();

            doc.font('Helvetica').fontSize(12);
            const avgGlucose = stats.avg_glucose ? Math.round(stats.avg_glucose) : '-';
            doc.text(`Average Glucose: ${avgGlucose} mg/dL`);

            // H7 FIX: Prevent division by zero
            const medsTaken = parseInt(stats.meds_taken) || 0;
            const medsMissed = parseInt(stats.meds_missed) || 0;
            const totalMeds = medsTaken + medsMissed;
            const adherence = totalMeds > 0 ? Math.round((medsTaken / totalMeds) * 100) : 0;
            doc.text(`Medication Adherence: ${adherence}%`);

            doc.text(`Symptom Reports: ${stats.symptom_reports || 0}`);
            doc.text(`Total Check-ins: ${stats.total_checkins || 0}`);

            // --- Disclaimer ---
            doc.moveDown(4);
            doc.fontSize(10).fillColor('grey')
                .text('This report is generated by Hanna AI Nurse for informational purposes only. It does not constitute a medical diagnosis.', { align: 'center' });

            doc.end();

        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generateReport };
