import { motion } from 'framer-motion'
import { AlertTriangle, Shield, FileText } from 'lucide-react'

export default function MedicalDisclaimer() {
    return (
        <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-8 p-4 bg-amber-50 border border-amber-200 rounded-xl"
        >
            <div className="flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                <div>
                    <h3 className="text-sm font-semibold text-amber-900 mb-1">
                        Not a Medical Device
                    </h3>
                    <p className="text-xs text-amber-800 leading-relaxed">
                        Hanna Scribe is a <strong>documentation assistant only</strong> and is not 
                        intended to diagnose, treat, or prevent any disease or medical condition. 
                        All clinical notes generated by AI must be reviewed, verified, and approved 
                        by a licensed healthcare provider before use in patient care.
                    </p>
                    <p className="text-xs text-amber-800 leading-relaxed mt-2">
                        The AI may make errors or omissions. Always exercise professional 
                        judgment and verify all information against your clinical assessment.
                    </p>
                </div>
            </div>
        </motion.div>
    )
}
