const translations = {
    en: {
        // Login
        'login.subtitle': 'Intelligent care partner',
        'login.email': 'Email',
        'login.pin': 'PIN',
        'login.signIn': 'Sign In',
        'login.remember': 'Remember this device',
        'login.newUser': 'New here?',
        'login.createAccount': 'Create account',
        'login.error': 'Invalid email or PIN',

        // Home
        'home.greeting.morning': 'Good morning',
        'home.greeting.afternoon': 'Good afternoon',
        'home.greeting.evening': 'Good evening',
        'home.commandBar': 'Ask Hanna...',
        'home.today': 'Today',
        'home.yesterday': 'Yesterday',
        'home.notes': 'notes',
        'home.noSessions': 'No sessions yet',
        'home.noSessionsSub': 'Tap + to start your first recording',

        // New Session
        'newSession.title': 'New Session',
        'newSession.patientName': 'Patient Name',
        'newSession.patientPlaceholder': 'Patient name (optional)',
        'newSession.hn': 'HN (optional)',
        'newSession.hnPlaceholder': 'Hospital Number',
        'newSession.template': 'Template',
        'newSession.start': 'Start Recording',

        // Recording
        'recording.listening': 'Listening...',
        'recording.paused': 'Paused',
        'recording.done': 'Done',
        'recording.discard': 'Discard recording?',
        'recording.discardConfirm': 'Discard',
        'recording.discardCancel': 'Keep recording',

        // Processing
        'processing.generating': 'Generating {template} note...',

        // Note
        'note.generatedBy': 'Generated by Hanna',
        'note.viewTranscript': 'View transcript',
        'note.edit': 'Edit',
        'note.export': 'Export',
        'note.finalize': 'Finalize',
        'note.amend': 'Amend',
        'note.draft': 'Draft · Not yet reviewed',
        'note.finalized': 'Clinician-reviewed',
        'note.copy': 'Copy',
        'note.pdf': 'Export PDF',

        // Editor
        'editor.editing': 'Editing',
        'editor.save': 'Save',
        'editor.tellHanna': 'Tell Hanna to edit...',
        'editor.cancel': 'Cancel',

        // Handover
        'handover.title': 'Shift Handover',
        'handover.generated': 'Generated from {count} sessions',
        'handover.patients': 'patients',
        'handover.urgent': 'urgent',
        'handover.avgTime': 'Avg encounter',
        'handover.min': 'min',
        'handover.copy': 'Copy',
        'handover.exportPdf': 'Export PDF',
        'handover.regenerate': 'Regenerate',

        // Settings
        'settings.title': 'Settings',
        'settings.profile': 'Profile',
        'settings.language': 'Language',
        'settings.appLang': 'App language',
        'settings.appLanguage': 'App language',
        'settings.noteLang': 'Note output',
        'settings.noteOutput': 'Note output',
        'settings.version': 'Version',
        'settings.defaults': 'Defaults',
        'settings.defaultTemplate': 'Default template',
        'settings.autoFinalize': 'Auto-finalize',
        'settings.about': 'About',
        'settings.help': 'Help & Feedback',
        'settings.signOut': 'Sign Out',

        // Templates
        'template.soap': 'SOAP',
        'template.progress': 'Progress',
        'template.free': 'Free',

        // Common
        'common.cancel': 'Cancel',
        'common.save': 'Save',
        'common.delete': 'Delete',
        'common.retry': 'Retry',
        'common.offline': 'Offline — recording saved locally',
    },

    th: {
        // Login
        'login.subtitle': 'ผู้ช่วยดูแลอัจฉริยะ',
        'login.email': 'อีเมล',
        'login.pin': 'รหัส PIN',
        'login.signIn': 'เข้าสู่ระบบ',
        'login.remember': 'จดจำอุปกรณ์นี้',
        'login.newUser': 'ยังไม่มีบัญชี?',
        'login.createAccount': 'ลงทะเบียน',
        'login.error': 'อีเมลหรือ PIN ไม่ถูกต้อง',

        // Home
        'home.greeting.morning': 'สวัสดีตอนเช้า',
        'home.greeting.afternoon': 'สวัสดีตอนบ่าย',
        'home.greeting.evening': 'สวัสดีตอนเย็น',
        'home.commandBar': 'ถาม Hanna...',
        'home.today': 'วันนี้',
        'home.yesterday': 'เมื่อวาน',
        'home.notes': 'บันทึก',
        'home.noSessions': 'ยังไม่มีบันทึก',
        'home.noSessionsSub': 'แตะ + เพื่อเริ่มบันทึกครั้งแรก',

        // New Session
        'newSession.title': 'บันทึกใหม่',
        'newSession.patientName': 'ชื่อผู้ป่วย',
        'newSession.patientPlaceholder': 'ชื่อผู้ป่วย (ไม่บังคับ)',
        'newSession.hn': 'HN (ไม่บังคับ)',
        'newSession.hnPlaceholder': 'เลขที่ผู้ป่วย',
        'newSession.template': 'แม่แบบ',
        'newSession.start': 'เริ่มบันทึก',

        // Recording
        'recording.listening': 'กำลังฟัง...',
        'recording.paused': 'หยุดชั่วคราว',
        'recording.done': 'เสร็จ',
        'recording.discard': 'ยกเลิกการบันทึก?',
        'recording.discardConfirm': 'ยกเลิก',
        'recording.discardCancel': 'บันทึกต่อ',

        // Processing
        'processing.generating': 'กำลังสร้าง {template} note...',

        // Note
        'note.generatedBy': 'สร้างโดย Hanna',
        'note.viewTranscript': 'ดู transcript',
        'note.edit': 'แก้ไข',
        'note.export': 'ส่งออก',
        'note.finalize': 'ยืนยัน',
        'note.amend': 'แก้ไขเพิ่มเติม',
        'note.draft': 'ร่าง · ยังไม่ได้ตรวจสอบ',
        'note.finalized': 'ตรวจสอบโดยแพทย์/พยาบาลแล้ว',
        'note.copy': 'คัดลอก',
        'note.pdf': 'ส่งออก PDF',

        // Editor
        'editor.editing': 'กำลังแก้ไข',
        'editor.save': 'บันทึก',
        'editor.tellHanna': 'บอก Hanna ให้แก้ไข...',
        'editor.cancel': 'ยกเลิก',

        // Handover
        'handover.title': 'สรุปส่งเวร',
        'handover.generated': 'สร้างจาก {count} รายการ',
        'handover.patients': 'ผู้ป่วย',
        'handover.urgent': 'เร่งด่วน',
        'handover.avgTime': 'เวลาเฉลี่ย',
        'handover.min': 'นาที',
        'handover.copy': 'คัดลอก',
        'handover.exportPdf': 'ส่งออก PDF',
        'handover.regenerate': 'สร้างใหม่',

        // Settings
        'settings.title': 'ตั้งค่า',
        'settings.profile': 'โปรไฟล์',
        'settings.language': 'ภาษา',
        'settings.appLang': 'ภาษาแอป',
        'settings.appLanguage': 'ภาษาแอป',
        'settings.noteLang': 'ภาษาบันทึก',
        'settings.noteOutput': 'ภาษาบันทึก',
        'settings.version': 'เวอร์ชัน',
        'settings.defaults': 'ค่าเริ่มต้น',
        'settings.defaultTemplate': 'แม่แบบเริ่มต้น',
        'settings.autoFinalize': 'ยืนยันอัตโนมัติ',
        'settings.about': 'เกี่ยวกับ',
        'settings.help': 'ช่วยเหลือ',
        'settings.signOut': 'ออกจากระบบ',

        // Templates
        'template.soap': 'SOAP',
        'template.progress': 'Progress',
        'template.free': 'อิสระ',

        // Common
        'common.cancel': 'ยกเลิก',
        'common.save': 'บันทึก',
        'common.delete': 'ลบ',
        'common.retry': 'ลองใหม่',
        'common.offline': 'ออฟไลน์ — บันทึกเสียงไว้ในเครื่อง',
    }
}

export function getLocale() {
    return localStorage.getItem('scribe_lang') || 'en'
}

export function setLocale(lang) {
    localStorage.setItem('scribe_lang', lang)
}

export function t(key, params = {}) {
    const lang = getLocale()
    let text = translations[lang]?.[key] || translations.en[key] || key
    Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v)
    })
    return text
}

export function getGreeting() {
    const hour = new Date().getHours()
    if (hour < 12) return t('home.greeting.morning')
    if (hour < 17) return t('home.greeting.afternoon')
    return t('home.greeting.evening')
}

// Aliases for Settings page
export const getLanguage = getLocale
export const setLanguage = setLocale

export function getNoteLanguage() {
    return localStorage.getItem('scribe_note_lang') || 'en'
}

export function setNoteLanguage(lang) {
    localStorage.setItem('scribe_note_lang', lang)
}

